### PR TITLE
Remove test classes

### PR DESCRIPTION
**Pull request by bebef1987**
Remove test classes as they are not necessary on pytests

Fix issue: #34

### CODE REVIEW

**Comment by davehunt** [comment]
I was hoping this would be taken for an Outreachy participant, but thanks for the patch @bebef1987. Please make sure your patch passes flake8 and make another comment when it's ready for review/merge.

**Comment by bebef1987** [comment]
@davehunt updated

**Comment by davehunt** [comment]
@bebef1987 please update to include `test_view_single_result.py`

**Comment by davehunt** [comment]
@bebef1987 are you still interested in working on this?

**Comment by rbillings** [comment]
Closing, will fix in a new PR.

**Pull request closed without merging**
