### PR TITLE
Set up flake8 checking with Travis-CI and resolve warnings

### PR DESCRIPTION
**Pull request by davehunt**
This will likely need rebasing after other pulls land, and I there's likely to be a failure here that I will address in an upcoming patch.

Pinging @tojonmz and @rbillings for review.

### CODE REVIEW

**Comment by davehunt** [comment]
This fixes #20

**Comment by davehunt** [comment]
Also pinging @camd for visibility/review.

**Comment by rbillings** [comment]
r+, verified flake8 now runs :monkey_face:

**Comment by stephendonner** [comment]
Yah, merging; thx, all!

**Comment by davehunt** [comment]
> there's likely to be a failure here that I will address in an upcoming patch

We're now seeing this failure. It should be resolved once the remaining pull requests land.

**Comment by stephendonner** [comment]
Thanks, Dave; and sorry if I shouldn't have merged that without you or the follow-up patches around/ready!

**Comment by davehunt** [comment]
No problem, it's all fixed now, and it's an unsupervised job in Jenkins so the failures didn't alert anyone.

**Pull request merged**
