### PR TITLE
Fix to address job_details and clear_pinboard failures

### PR DESCRIPTION
**Pull request by rbillings**
This job was failing as the job_details pane was open but the data hadn't fully loaded when the test tried to add it to the pinboard. This change should get both pinboard tests passing.

### CODE REVIEW

**Comment by stephendonner** [comment]
Hmm, I've run this numerous times on Firefox 47.0.2 on macOS, and I still see failures in both tests:

```
sdonner-17447:treeherder-tests sdonner$ git branch
* clear_pinboard
  master

<snip>

________________________ test_pin_job_from_job_details _________________________
[gw5] darwin -- Python 2.7.10 /Users/sdonner/treeherder-tests/.tox/tests/bin/python
base_url = 'https://treeherder.allizom.org'
selenium = <selenium.webdriver.firefox.webdriver.WebDriver (session="3ab22d51-ddfb-8d44-af85-2883df2052d6")>

    def test_pin_job_from_job_details(base_url, selenium):
        """Open treeherder page, select first job, pin it by the pin icon"""
        page = TreeherderPage(selenium, base_url).open()
>       job = page.result_sets[0].jobs[0]
E       IndexError: list index out of range

tests/test_pin_job.py:22: IndexError
------------------------------- pytest-selenium --------------------------------
URL: https://treeherder.allizom.org/#/jobs?repo=mozilla-inbound
_____________________________ test_clear_pinboard ______________________________
[gw3] darwin -- Python 2.7.10 /Users/sdonner/treeherder-tests/.tox/tests/bin/python
base_url = 'https://treeherder.allizom.org'
selenium = <selenium.webdriver.firefox.webdriver.WebDriver (session="464e3ad3-20c7-0c4e-9b2a-062fdba003a3")>

    def test_clear_pinboard(base_url, selenium):
        """Open treeherder page, pin a job and then clear the pinboard"""
        page = TreeherderPage(selenium, base_url).open()
>       page.result_sets[0].jobs[0].click()
E       IndexError: list index out of range

tests/test_pin_job.py:33: IndexError
```

My debugging skills are next to nothing, sorry :-(

**Comment by stephendonner** [comment]
@rbillings when you get a chance, could you rebase this with master, and I'll take another look?  Thanks!

**Comment by rbillings** [comment]
Branch updated, r?

**Comment by rbillings** [comment]
Ready for review

**Pull request merged**
