### PR TITLE
Update pytest to 3.0.0

### PR DESCRIPTION
**Pull request by stephendonner**
@mozilla/web-qa-apprentices / @mozilla/web-qa-sorcerers r?

### CODE REVIEW

**Comment by stephendonner** [comment]
Ad-hoc job results (passing) here: https://pastebin.mozilla.org/8904021

**Comment by davehunt** [comment]
Nice, thanks @stephendonner! There's a warning that we can clean up too:

> WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.

**Comment by davehunt** [comment]
r+ wc

**Comment by stephendonner** [comment]
Final ad-hoc results with change to setup.cfg (all passing): https://pastebin.mozilla.org/8904185

**Pull request merged**
